import allure
import pytest
from conftest import driver
from page_objects.faq_page import FaqPage
from helpers.locators.locators_faq_page import (
    ACCORDION_QUESTION_COST, ANSWER_QUESTION_COST,
    ACCORDION_QUESTION_SEVERAL_SCOOTER, ANSWER_QUESTION_SEVERAL_SCOOTER,
    ACCORDION_QUESTION_RENTAL_TIME, ANSWER_QUESTION_RENTAL_TIME,
    ACCORDION_QUESTION_ORDER_TODAY, ANSWER_QUESTION_ORDER_TODAY,
    ACCORDION_QUESTION_EXTEND_OR_RETURN, ANSWER_QUESTION_EXTEND_OR_RETURN,
    ACCORDION_QUESTION_CHARGER_INCLUDED, ANSWER_QUESTION_CHARGER_INCLUDED,
    ACCORDION_QUESTION_CANCEL_ORDER, ANSWER_QUESTION_CANCEL_ORDER,
    ACCORDION_QUESTION_OUTSIDE_MKAD, ANSWER_QUESTION_OUTSIDE_MKAD
)
from helpers.constants.constants_faq_page import (
    EXPECTED_RESULT_QUESTION_CANCEL_ORDER, EXPECTED_RESULT_QUESTION_OUTSIDE_MKAD,
    EXPECTED_RESULT_QUESTION_COST, EXPECTED_RESULT_QUESTION_RENTAL_TIME,
    EXPECTED_RESULT_QUESTION_ORDER_TODAY, EXPECTED_RESULT_QUESTION_CHARGER_INCLUDED,
    EXPECTED_RESULT_QUESTION_EXTEND_OR_RETURN, EXPECTED_RESULT_QUESTION_SEVERAL_SCOOTERS
)

faq_test_data = [
    pytest.param(ACCORDION_QUESTION_COST, ANSWER_QUESTION_COST, EXPECTED_RESULT_QUESTION_COST, id="QUESTION_COST"),
    pytest.param(ACCORDION_QUESTION_SEVERAL_SCOOTER, ANSWER_QUESTION_SEVERAL_SCOOTER, EXPECTED_RESULT_QUESTION_SEVERAL_SCOOTERS, id="QUESTION_SEVERAL_SCOOTER"),
    pytest.param(ACCORDION_QUESTION_RENTAL_TIME, ANSWER_QUESTION_RENTAL_TIME, EXPECTED_RESULT_QUESTION_RENTAL_TIME, id="QUESTION_RENTAL_TIME"),
    pytest.param(ACCORDION_QUESTION_ORDER_TODAY, ANSWER_QUESTION_ORDER_TODAY, EXPECTED_RESULT_QUESTION_ORDER_TODAY, id="QUESTION_ORDER_TODAY"),
    pytest.param(ACCORDION_QUESTION_EXTEND_OR_RETURN, ANSWER_QUESTION_EXTEND_OR_RETURN, EXPECTED_RESULT_QUESTION_EXTEND_OR_RETURN, id="QUESTION_EXTEND_OR_RETURN"),
    pytest.param(ACCORDION_QUESTION_CHARGER_INCLUDED, ANSWER_QUESTION_CHARGER_INCLUDED, EXPECTED_RESULT_QUESTION_CHARGER_INCLUDED, id="QUESTION_CHARGER_INCLUDED"),
    pytest.param(ACCORDION_QUESTION_CANCEL_ORDER, ANSWER_QUESTION_CANCEL_ORDER, EXPECTED_RESULT_QUESTION_CANCEL_ORDER, id="QUESTION_CANCEL_ORDER"),
    pytest.param(ACCORDION_QUESTION_OUTSIDE_MKAD, ANSWER_QUESTION_OUTSIDE_MKAD, EXPECTED_RESULT_QUESTION_OUTSIDE_MKAD, id="QUESTION_OUTSIDE_MKAD")
]

class TestFaqSection:
    @pytest.mark.parametrize("question_locator, answer_locator, expected_text", faq_test_data)
    def test_faq_section(self, driver, question_locator, answer_locator, expected_text):
        faq_page = FaqPage(driver)
        faq_page.open_browser()
        faq_page.scroll_to_faq_section()
        faq_page.click_question(question_locator)
        faq_page.check_answer_text(answer_locator, expected_text)
